# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf265a68a421a2c5217a119e5c38e81ac121a5e11ae8560e7efc99563b246f53f7ab3113675ffa4ad6686ef702a8fb98164589c87f2a08d402ed5e8da4fcfe9

test:
  secret_key_base: 9f4e04b08ebb8e32f8a3f71f03b70c01931bc26cc27b404199ad3b75f4ad50eee03fc33430a1aa3944cf664e0930f4d9249d586c8b264b84fa7324f279c493ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
